server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aaa3?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: itheima
  thymeleaf:
    suffix: .html


mybatis:
  type-aliases-package: com.hehe.demo3.bean
#  mapper-locations: classpath:mapper/*Mapper.xml

mybatis-plus:
  configuration:
    #    日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.hehe.demo3.bean



