server:
  port: 8001
spring:
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: itheima
    url: jdbc:mysql://localhost:3306/aaa3?serverTimezone=GMT%2B8&useSSL=true
#    url: jdbc:mysql://localhost:3306/aaa3
#  thymeleaf:
#    suffix: .html

