server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aaa3?serverTimezone=GMT%2B8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: itheima

mybatis-plus:
  configuration:
    #    日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.springswager.entrny



